#!/bin/sh
fpm_conf_file=/app-home/.php/fpm/php.ini

# Create directory for fpm_conf_file if not present
mkdir -p $(dirname $fpm_conf_file)

# Configure XDebug for PHP-FPM
# If host.docker.internal is resolvable, use it as remote host
# Otherwise, use user defined remote host or connect back mechanism
echo "zend_extension=xdebug.so
xdebug.remote_enable=1
xdebug.remote_autostart=1
xdebug.remote_port=${XDEBUG_REMOTE_PORT:-9000}
xdebug.remote_mode=req" > $fpm_conf_file
if [ "$XDEBUG_REMOTE_HOST" != "" ]; then
    echo "xdebug.remote_host=${XDEBUG_REMOTE_HOST}" >> $fpm_conf_file
elif nslookup host.docker.internal > /dev/null; then
    echo "xdebug.remote_host=host.docker.internal" >> $fpm_conf_file
else
    echo "xdebug.remote_connect_back=1" >> $fpm_conf_file
fi

# Configure easy access for MySQL
if [ ! -e "${HOME}/.my.cnf" ]; then
    echo "[client]
host = db
user = ${MYSQL_USER}
password = ${MYSQL_PASSWORD}
database = ${MYSQL_DATABASE}" > ${HOME}/.my.cnf
fi

# Configure MSMTP
if [ -n "$SENDMAIL_SMTP_HOST" ]; then
    msmtprc_file=/app-home/.msmtprc
    echo "defaults
port ${SENDMAIL_SMTP_PORT:-25}
tls ${SENDMAIL_SMTP_TLS:-off}
tls_trust_file /etc/ssl/certs/ca-certificates.crt

account mail
host $SENDMAIL_SMTP_HOST
from ${SENDMAIL_SMTP_FROM:-magento@internal.app}
auth ${SENDMAIL_SMTP_AUTH:-off}
user ${SENDMAIL_SMTP_USER:-user}
password ${SENDMAIL_SMTP_PASSWORD:-password}

account default : mail" > $msmtprc_file
    chmod 0600 $msmtprc_file
fi

# Execute composer install if required
if [ "$COMPOSER_INSTALL_ON_BOOT" = "true" ]; then
    composer install
fi

##
exec /usr/local/bin/docker-php-entrypoint "$@"
