#!/bin/sh

# Create directory structure for PHP-FPM configuration if not present
mkdir -p $HOME/.php/fpm

# Configure PHP
nslookup host.docker.internal > /dev/null
HOST_DOCKER_INTERNAL_ACCESSIBLE=$? dockerize -template \
    /entrypoint-templates/php/fpm/php.ini.tpl > $HOME/.php/fpm/php.ini

# Configure easy access to MariaDB/MySQL database
dockerize -template \
    /entrypoint-templates/my.cnf.tpl > $HOME/.my.cnf

# Configure MSMTP
if [ -n "$SENDMAIL_SMTP_HOST" ]; then
    msmtprc_file=$HOME/.msmtprc
    dockerize -template \
        /entrypoint-templates/msmtprc.tpl > $msmtprc_file
    chmod 0600 $msmtprc_file
fi

# Execute composer install if required
if [ "$COMPOSER_INSTALL_ON_BOOT" = "true" ]; then
    composer install
fi

##
exec /usr/local/bin/docker-php-entrypoint "$@"
