version: '3'

services:

    app:
        user: ${UID:-1000}:${GID:-1000}
        image: magently/mde-php-${PHP_VERSION}:0.1.1
        build:
            context: ./docker/php
            args:
                php_version: ${PHP_VERSION}
        volumes:
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
            - ${SSH_DIRECTORY:-~/.ssh}:$HOME/.ssh:ro
            - ${NPM_DIRECTORY:-~/.npm}:/app-home/.npm:delegated
            - ${COMPOSER_AUTH_FILE:-/dev/null}:/app-home/.composer/auth.json:ro
            - ${COMPOSER_CACHE_DIRECTORY:-~/.composer/cache}:/app-home/.composer/cache:delegated
            - ${MAGENTO_PATH}:/app:delegated
        environment:
            - COMPOSER_INSTALL_ON_BOOT
            - COMPOSER_AUTH
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_DATABASE
            - PHP_IDE_CONFIG=serverName=docker_dev_${COMPOSE_PROJECT_NAME}
            - XDEBUG_ENABLED
            - XDEBUG_REMOTE_HOST
            - XDEBUG_REMOTE_PORT
            - SENDMAIL_SMTP_HOST
            - SENDMAIL_SMTP_PORT
            - SENDMAIL_SMTP_AUTH
            - SENDMAIL_SMTP_TLS
            - SENDMAIL_SMTP_USER
            - SENDMAIL_SMTP_PASSWORD
            - SENDMAIL_SMTP_FROM

    db:
        image: magently/mde-mariadb:0.1.1
        build: ./docker/mariadb
        volumes:
            - ${MYSQL_USER_DIRECTORY:-/dev/null}:/var/lib/mysql-user
            - mysql-volume:/var/lib/mysql-volume
        env_file:
            - .env
        environment:
            - USER_UID=${UID:-1000}
            - USER_GID=${GID:-1000}
            - MYSQL_ROOT_PASSWORD
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_DATABASE

    web:
        image: magently/mde-nginx:0.1.1
        build: ./docker/nginx
        volumes:
            - ${MAGENTO_PATH}:/app:ro
        ports:
            - ${HTTP_EXTERNAL_PORT}:80
        environment:
            - VARNISH_ENABLED
            - HTTP_EXTERNAL_PORT
            - PROXY_THROUGH
            - MAGENTO_1_MODE

volumes:
    mysql-volume:
