version: '3'

services:

    app:
        build:
            context: ./docker/magento
            args:
                php_version: ${PHP_VERSION}
        user: ${UID}:${GID}
        volumes:
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
            - ${HOME}/.ssh/:${HOME}/.ssh
            - ${MAGENTO_PATH}:/app
            - ${COMPOSER_AUTH_FILE}:/composer_home/auth.json:ro
            - ${HOME}/.composer/cache:/composer_home/cache
        env_file:
            - .env

    db:
        image: mariadb
        user: ${UID}:${GID}
        volumes:
            - ./storage/mysql:/var/lib/mysql
        env_file:
            - .env

    web:
        build: ./docker/nginx
        volumes:
            - ${MAGENTO_PATH}:/app
        ports:
            - ${HTTP_EXTERNAL_PORT}:80
        environment:
            - VARNISH_ENABLED
