version: '3'

services:

    app:
        build:
            context: ./docker/magento
            args:
                php_version: ${PHP_VERSION}
        user: ${UID:-1000}:${GID:-1000}
        volumes:
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
            - ${HOME}/.ssh/:${HOME}/.ssh:ro
            - ${MAGENTO_PATH}:/app
            - ${COMPOSER_AUTH_FILE:-/dev/null}:/composer_home/auth.json:ro
            - ${HOME}/.composer/cache:/composer_home/cache
            - ${HOME}/.npm:${HOME}/.npm
        environment:
            - COMPOSER_INSTALL_ON_BOOT
            - COMPOSER_AUTH
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_DATABASE

    db:
        image: mariadb
        user: ${UID}:${GID}
        volumes:
            - ./storage/mysql:/var/lib/mysql
        env_file:
            - .env
        environment:
            - MYSQL_ROOT_PASSWORD
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_DATABASE

    web:
        build: ./docker/nginx
        volumes:
            - ${MAGENTO_PATH}:/app:ro
        ports:
            - ${HTTP_EXTERNAL_PORT}:80
        environment:
            - VARNISH_ENABLED
            - HTTP_EXTERNAL_PORT
            - PROXY_TARGET
            - MAGENTO_1_MODE
