version: '3'

services:

    app:
        user: ${UID}:${GID}
        build:
            context: ./docker/magento
            args:
                php_version: ${PHP_VERSION}
        volumes:
            - ${HOME}/.ssh:/app-home/.ssh:ro
            - ${HOME}/.npm:/app-home/.npm
            - ${COMPOSER_AUTH_FILE:-/dev/null}:/app-home/.composer/auth.json:ro
            - ${HOME}/.composer/cache:/app-home/.composer/cache
            - ${MAGENTO_PATH}:/app
        environment:
            - COMPOSER_INSTALL_ON_BOOT
            - COMPOSER_AUTH
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_DATABASE
            - PHP_IDE_CONFIG=serverName=docker_dev_${COMPOSE_PROJECT_NAME}

    db:
        build: ./docker/mariadb
        volumes:
            - ${MYSQL_USER_DIRECTORY:-/dev/null}:/var/lib/mysql-user
            - mysql-volume:/var/lib/mysql-volume
        env_file:
            - .env
        environment:
            - USER_UID=${UID:-1000}
            - USER_GID=${GID:-1000}
            - MYSQL_ROOT_PASSWORD
            - MYSQL_USER
            - MYSQL_PASSWORD
            - MYSQL_DATABASE

    web:
        build: ./docker/nginx
        volumes:
            - ${MAGENTO_PATH}:/app:ro
        ports:
            - ${HTTP_EXTERNAL_PORT}:80
        environment:
            - VARNISH_ENABLED
            - HTTP_EXTERNAL_PORT
            - PROXY_TARGET
            - MAGENTO_1_MODE

volumes:
    mysql-volume:
