version: '3'

services:

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        ports:
            - ${PHPMYADMIN_EXTERNAL_PORT:-8336}:80
        environment:
            PMA_HOST: db
            PMA_USER: root
            PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
