#!/bin/sh

if [ "$PROXY_THROUGH" != "" ]; then
    export MAGENTO_PORT=58080
    dockerize -template /etc/nginx/templates/proxy.tmpl > /etc/nginx/conf.d/proxy.conf
else
    export MAGENTO_PORT=80
    [ $HTTP_EXTERNAL_PORT == 80 ] && export HTTP_EXTERNAL_PORT_DEFAULT=1
    [ -e /etc/nginx/conf.d/proxy.conf ] && rm /etc/nginx/conf.d/proxy.conf
fi

[ "$MAGENTO_1_MODE" == "true" ] && magento_file='magento1.tmpl' || magento_file='magento2.tmpl'
dockerize -template /etc/nginx/templates/$magento_file > /etc/nginx/conf.d/magento.conf

exec "$@"
