#!/bin/sh

if [ ! -e "${HOME}/.my.cnf" ]; then
    echo "[client]
host = db
user = ${MYSQL_USER}
password = ${MYSQL_PASSWORD}
database = ${MYSQL_DATABASE}" > ${HOME}/.my.cnf
fi

if [ "$COMPOSER_INSTALL_ON_BOOT" = "true" ]; then
    composer install
fi

# Configure XDebug
# If host.docker.internal is resolvable, use it as remote host
# Otherwise, use default gateway
echo "zend_extension=xdebug.so
xdebug.remote_enable=1
xdebug.remote_autostart=1
xdebug.remote_port=${XDEBUG_REMOTE_PORT:-9000}
xdebug.remote_mode=req" > /app-home/xdebug.ini
if [ "$XDEBUG_REMOTE_HOST" != "" ]; then
    echo "xdebug.remote_host=${XDEBUG_REMOTE_HOST}" >> /app-home/xdebug.ini
elif nslookup host.docker.internal > /dev/null; then
    echo "xdebug.remote_host=host.docker.internal" >> /app-home/xdebug.ini
else
    echo "xdebug.remote_connect_back=1" >> /app-home/xdebug.ini
fi

##
exec /usr/local/bin/docker-php-entrypoint "$@"
